
### DATABASE ###
db-default-queuery-timeout: 5s

db-skip-post-connection: true

### CACHE ###
cache-pool-timeout: 200ms

cache-operation-timeout: 100ms

cache-ttl: 5m

### DEBUG ####
debug-mode: true

debug-safe-db-scans: true

debug-log-db-queries: true

### APP ###
service-id: 5466e0e6-0c20-4cc3-90aa-2a2c731ce49d

show-logs: true

trace-logs: true

### SENTRY ###

sentry-trace-sample-rate: 0.1 # 10%

