### APP ###
service-id: de5a61bd-a0af-493c-8442-e1f92c5c2933
show-logs: true
trace-logs: true

### DEBUG ####
debug-mode: true
debug-safe-db-scans: true
debug-log-db-queries: true

### DATABASE ###
db-default-queuery-timeout: 5s
db-skip-post-connection: false

### CACHE ###
cache-pool-timeout: 200ms
cache-operation-timeout: 100ms
cache-ttl: 5m

### SENTRY ###
sentry-trace-sample-rate: 0.1 # 10%

